2019-11-23 15:37:16.839173: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-11-23 15:37:16.867227: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-11-23 15:37:16.868664: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: laser-compressor-3000
2019-11-23 15:37:16.868717: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: laser-compressor-3000
2019-11-23 15:37:16.868809: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.104.0
2019-11-23 15:37:16.868878: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.104.0
2019-11-23 15:37:16.868944: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.104.0
Traceback (most recent call last):
  File "../exps/ttest.py", line 117, in <module>
    result_dicts.append(experiment.train())
  File "../src/experiment.py", line 86, in train
    result_dict['va']['loss'][-1]))
OSError: [Errno 5] Input/output error
rm: write error: Input/output error
