2019-11-23 15:35:22.026240: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-11-23 15:35:22.031455: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-11-23 15:35:22.031560: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: nina
2019-11-23 15:35:22.031678: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: nina
2019-11-23 15:35:22.031837: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.104.0
2019-11-23 15:35:22.031907: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.104.0
2019-11-23 15:35:22.031961: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.104.0
Traceback (most recent call last):
  File "../exps/ttest.py", line 117, in <module>
    result_dicts.append(experiment.train())
  File "../src/experiment.py", line 86, in train
    result_dict['va']['loss'][-1]))
OSError: [Errno 5] Input/output error
rm: write error: Input/output error
